route:
  receiver: default
  group_by: ["alertname", "job", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: default
    webhook_configs:
      - url: "http://example.com/alertmanager-webhook"
        send_resolved: true
